### ISSUE TITLE
Add type of Gradle distribution to the custom distribution filename

### ISSUE THREAD

**Issue by tudortimi** [denis-zhdanov/custom-gradle-dist-gradle-plugin#10]
Currently, the custom distribution zip file name only contains `gradle-${version}`. If users want to produce the custom distribution in both `bin` and `all` flavors, they have to rename the file produced by the plugin.

**Comment by denis-zhdanov** [comment]
fixed in `1.10.0`

**Comment by tudortimi** [comment]
Wouldn't it be better to put the distribution type before the project name, though? This way there's a better separation between "native" Gradle name components and project name components.

So `gradle-dist/gradle-$GRADLE_VERSION-bin-$PROJECT_NAME-$PROJECT_VERSION.zip` instead of `gradle-dist/gradle-$GRADLE_VERSION-$PROJECT_NAME-$PROJECT_VERSION-bin.zip`

**Comment by denis-zhdanov** [comment]
yeah, I thought about that and it seems that in a situation when there are multiple custom distributions of the same version and variants like `all` and `bin`, it's more convenient to see that as `gradle-8.4-my-company-3.2.1-bin.zip` and `gradle-8.4-my-company-3.2.1-all.zip` than `gradle-8.4-bin-my-company-3.2.1.zip` and `gradle-8.4-all-my-company-3.2.1.zip`

**Comment by tudortimi** [comment]
I can see how that would be useful as well. Doesn't it get confusing when defining a custom distribution type, though? You end up with `gradle-8.4-my-company-3.2.1-my-custom-distro-bin.zip`. It's difficult to parse where the custom part is and where the Gradle part is.

I'm referring to this: https://github.com/harmonhsoft-tech/custom-gradle-dist-gradle-plugin/blob/99d3bf425b3937ec123de5313bdfe43a57b51961/src/main/kotlin/tech/harmonysoft/oss/gradle/dist/BuildCustomGradleDistributionTask.kt#L145C36-L145C36

**Comment by tudortimi** [comment]
Maybe it also makes sense to allow users to customize the file name: #11.
