### ISSUE TITLE
Add possibility to customize the naming of the custom distribution file

### ISSUE THREAD

**Issue by tudortimi** [denis-zhdanov/custom-gradle-dist-gradle-plugin#11]
It would be great if users could configure the name of the custom distribution file. 

This could be done with something like a `gradleDist.customDistributionFileNameMapper` function. It would work like `gradleDist.rootUrlMapper`, which gets the Gradle version, distribution type, custom distribution name and version.

**Comment by denis-zhdanov** [comment]
addressed in `1.12.0`
