### ISSUE TITLE
Problems with include your plugin after your today changes

### ISSUE THREAD

**Issue by piotrminkina** [denis-zhdanov/custom-gradle-dist-gradle-plugin#16]
@denis-zhdanov I don't know why, but the following change caused me to not be able to use this plugin via `includeBuild('...')`

https://github.com/harmonysoft-tech/custom-gradle-dist-gradle-plugin/blob/adb09a641f71322df722e722eb45f156adf82a36/build.gradle.kts#L5

When I change the version to `1.8.0`, then everything works correctly, i.e. the plugin is included and my custom gradle distributions build correctly. When I change the version to `1.9.0`, then an error like the following appears, at the stage of including your plugin:

```quote
* Where:
Settings file '[...]/my-gradle-distribution-customizations/settings.gradle' line: 6

* What went wrong:
Error resolving plugin [id: 'com.example.my-gradle-distribution-customizations']
> A problem occurred configuring project ':custom-gradle-dist-gradle-plugin'.
   > java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file [...]/.gradle/caches/jars-9/d1dc929292e759a12b7b66ca35ee6dc6/gradle-release-paperwork-1.9.0.jar.
```

When I change the version to `1.10.0`, then an error like the following appears, at the stage of compiling my customization plugin:

```quote
[...]

> Task :custom-gradle-dist-gradle-plugin:jar
:jar: A valid plugin descriptor was found for tech.harmonysoft.oss.custom-gradle-dist-plugin.properties but the implementation class tech.harmonysoft.oss.gradle.dist.CustomGradleDistributionPlugin was not found in the jar.

> Task :compileGroovy FAILED
startup failed:
[...]/my-gradle-distribution-customizations/src/main/groovy/[...]/GradleDistributionPlugin.groovy: 15: unable to resolve class tech.harmonysoft.oss.gradle.dist.BuildCustomGradleDistributionTask
 @ line 15, column 1.
   import tech.harmonysoft.oss.gradle.dist.BuildCustomGradleDistributionTask
   ^

[...]/my-gradle-distribution-customizations/src/main/groovy/[...]/GradleDistributionPlugin.groovy: 16: unable to resolve class tech.harmonysoft.oss.gradle.dist.CustomGradleDistributionPlugin
 @ line 16, column 1.
   import tech.harmonysoft.oss.gradle.dist.CustomGradleDistributionPlugin
   ^

[...]/my-gradle-distribution-customizations/src/main/groovy/[...]/GradleDistributionPlugin.groovy: 17: unable to resolve class tech.harmonysoft.oss.gradle.dist.config.CustomGradleDistConfig
 @ line 17, column 1.
   import tech.harmonysoft.oss.gradle.dist.config.CustomGradleDistConfig
   ^

3 errors
```

**Comment by piotrminkina** [comment]
OK, it dawned on me. The produced jar package is almost empty. Some bug crept into the `tech.harmonysoft.oss.gradle.release.paperwork` plugin. Se the following screenshot.

![image](https://github.com/harmonysoft-tech/custom-gradle-dist-gradle-plugin/assets/2574153/6a6339d3-bce8-4d2a-91d3-c3595b0e1a0e)

**Comment by denis-zhdanov** [comment]
could you double-check that with a released plugin version (`1.19.0`)? I just checked it with my own custom distribution it works just fine - [source](https://github.com/harmonysoft-tech/kotlin-spring-gradle-dist/blob/main/build.gradle.kts#L5) -> [build](https://github.com/harmonysoft-tech/kotlin-spring-gradle-dist/actions/runs/8785076938/job/24104700367)

**Comment by piotrminkina** [comment]
Now works fine, but if You interested, before commit d4416f88 inclusive this problem occurs. After commit 19d83de8 inclusive all works fine now.

**Comment by piotrminkina** [comment]
Interestingly, the problem does not exist when I use the published version 1.18.0 of the plugin. I suppose it could be something about the Java version. To build the included plug-in, I first have to run the `JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64` command.

**Comment by piotrminkina** [comment]
Anyway, I think You can close this issue.

**Comment by denis-zhdanov** [comment]
```
To build the included plug-in, I first have to run the JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 command.
```

That's weird, the plugin is configured to use java8 toolchain - https://github.com/harmonysoft-tech/gradle-release-paperwork/blob/main/build.gradle.kts#L12

**Comment by piotrminkina** [comment]
That's interesting, because when I tried to compile the extension on the default Java 14, I got Gradle screaming that it couldn't find the right tools, but unfortunately I didn't look at the messages, I just immediately assumed it was about a newer version of Java. I currently have multiple versions of Java installed on my system:

 + AdoptOpenJDK 13.0.2+8
 + Amazon Corretto JDK 1.8.0_402-b08
 + Amazon Corretto JDK 11.0.12+7-LTS
 + Eclipse Temurin JDK 11.0.22+7
 + Private Build JDK 1.8.0_402-8u402-ga-2ubuntu1~22.04-b06
 + Private Build JDK 14.0.2+12-Ubuntu-120.04
 + Private Build JDK 19.0.2+7-Ubuntu-0ubuntu322.04
 + Private Build JDK 21.0.2+13-Ubuntu-122.04.1
 + Ubuntu JDK 11.0.22+7-post-Ubuntu-0ubuntu222.04.1

And these are my defaults:
```console
$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
$ javac -version
javac 14.0.2
```

On the other hand, the problem I reported does not appear to depend on the Java version. When I set the variable JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64, the problem is the same.

With commit d4416f8 :
```console
$ gradlew assemble
[...]
> Task :plugins:gradle-distribution:compileGroovy FAILED
startup failed:
[...]/gradleDistribution/plugins/GradleDistributionPlugin.groovy: 17: unable to resolve class tech.harmonysoft.oss.gradle.dist.BuildCustomGradleDistributionTask
 @ line 17, column 1.
   import tech.harmonysoft.oss.gradle.dist.BuildCustomGradleDistributionTask
[...]
```

With commit 19d83de:
```
$ gradlew assemble
[...]
BUILD SUCCESSFUL
```

This only happens when I include your plugin in my conventions plugin, via `includeBuild('...')` in `settings.gradle`.
