### ISSUE TITLE
Support replacement / merging of parameters from a source file

### ISSUE THREAD

**Issue by zerocode** [denis-zhdanov/custom-gradle-dist-gradle-plugin#4]
It would be nice to be able to define a single file of dependency version variables and be able to merge these versions through parameter replacement, eg:

in 'versions.gradle':

$junitJupiterVersion = 5.0
$springbootVersion = 2.4.3

then replacement in target file:

testImplementation "org.junit.jupiter:junit-jupiter:$junitJupiterVersion"

this would allow maintaining dependency versions in one place

**Comment by denis-zhdanov** [comment]
sorry, what exactly do you suggest?

The feature you mentioned is already supported

**Comment by zerocode** [comment]
Not quite. Currently each version variable requires its own file (as per the example in the readme). It would be convenient if all versions could be defined as variables in a _single file_ and the contents of that single file are used as replacements wherever the version parameters appear.

**Comment by denis-zhdanov** [comment]
ok, thanks, I see what you mean. The preprocessor functionality solves the task in general but doesn't offer such specific support for versions replacement.

Moreover, I see it not as a version replacement but as general multiple-replacement-rules-in-single-file functionality. I.e. there might be a property-like file(s) whose name and/or location pattern follow some convention and each line of such input defines a particular preprocessor rule. That way there might be a file like `versions.properties` and its contents would be like below:

```
junitJupiterVersion = 5.0
springbootVersion = 2.4.3
```

That task is not on top of my priority list for this project, however, contributions are welcome ;)

**Comment by zerocode** [comment]
Yes, that's exactly how I see it, a fine grained general purpose replacement mechanism. I'll see if I can find time for a PR. No promises ;)

**Comment by denis-zhdanov** [comment]
addressed in `1.13.0`
