### ISSUE TITLE
Add a gradle.properties to the distribution?

### ISSUE THREAD

**Issue by sourcedelica** [denis-zhdanov/custom-gradle-dist-gradle-plugin#6]
Is it possible to add a `gradle.properties` to the distribution?  If there is a `gradle.properties` at the root of the distribution (not in `init.d`) it will be used by `gradlew`.

Ref: https://github.com/gradle/gradle/issues/8269

**Comment by denis-zhdanov** [comment]
you can easily setup your distribution for that:

```
task installGradleProperties(type: Copy) {
    from new File(System.getProperty("gradle-dist.init.d.path"), 'misc/gradle.properties')
    into { rootProject.rootDir }
}

assemble.dependsOn installGradleProperties
```

**Comment by sourcedelica** [comment]
Thanks for your quick response!
