### ISSUE TITLE
Use `project.version` as default for `gradleDist.customDistributionVersion`

### ISSUE THREAD

**Issue by tudortimi** [denis-zhdanov/custom-gradle-dist-gradle-plugin#7]
Using the project's version is a reasonable default. It follows the Gradle philosophy of "convention over configuration".

**Comment by piotrminkina** [comment]
@tudortimi Code Review please :)

**Comment by tudortimi** [comment]
@piotrminkina I'm not the repo owner :D

**Comment by piotrminkina** [comment]
@tudortimi I know that, but what's the problem? You can always contribute in such a way to at least test it. You can download the repo and include it using `includeBuild()` in `settings.gradle`.
