### ISSUE TITLE
Name of task that produces the custom distribution conflicts with task from `base` plugin

### ISSUE THREAD

**Issue by tudortimi** [denis-zhdanov/custom-gradle-dist-gradle-plugin#9]
The task that produces the custom distribution is called `build`. This conflicts with the name used by the `base` plugin: https://docs.gradle.org.cn/current/userguide/base_plugin.html

I'd like to be able to apply this plugin, together with the `base` plugin, so I can configure publishing using the `archives` configuration.

**Comment by denis-zhdanov** [comment]
fixed in `1.11.0`
